// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdgGkek8Fi3Ny7uNfUdgbwz0s9OUExNbE',
    appId: '1:591436105536:ios:88abd1ae810eaf23c51ca5',
    messagingSenderId: '591436105536',
    projectId: 'blocproject-cef27',
    storageBucket: 'blocproject-cef27.firebasestorage.app',
    iosBundleId: 'com.example.signInProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAdgGkek8Fi3Ny7uNfUdgbwz0s9OUExNbE',
    appId: '1:591436105536:ios:88abd1ae810eaf23c51ca5',
    messagingSenderId: '591436105536',
    projectId: 'blocproject-cef27',
    storageBucket: 'blocproject-cef27.firebasestorage.app',
    iosBundleId: 'com.example.signInProject',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDyJh9eKiq2eVqrmKT6xa_1F9NmHXDykyE',
    appId: '1:591436105536:web:c65095d09079b4e7c51ca5',
    messagingSenderId: '591436105536',
    projectId: 'blocproject-cef27',
    authDomain: 'blocproject-cef27.firebaseapp.com',
    storageBucket: 'blocproject-cef27.firebasestorage.app',
    measurementId: 'G-9SPRXZ0HD8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAuRtlwpR8Z_lG50ha_8XUh7jwXqeLuWN0',
    appId: '1:591436105536:android:6092ccfe17ed5644c51ca5',
    messagingSenderId: '591436105536',
    projectId: 'blocproject-cef27',
    storageBucket: 'blocproject-cef27.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDyJh9eKiq2eVqrmKT6xa_1F9NmHXDykyE',
    appId: '1:591436105536:web:97184fd4c753a9b9c51ca5',
    messagingSenderId: '591436105536',
    projectId: 'blocproject-cef27',
    authDomain: 'blocproject-cef27.firebaseapp.com',
    storageBucket: 'blocproject-cef27.firebasestorage.app',
    measurementId: 'G-DH1PQXYCTX',
  );

}